language: ruby
rvm:
- 2.1.1
cache: bundler
script: echo "Nothing to build."
deploy:
  provider: s3
  access_key_id: AKIAIZY56TD54JM32ZFA
  secret_access_key:
    secure: vijuU1Eaau50XAcw55vQi5n0/YQfWnhOYRJU23P0iieJvymGGM0r/wdBd52TVZWYxkHVIKRPoHgtxm4A2GjWujDjtWmJYjdteg4fa4PJdwQODf2IR3f1Lug/DjwcRZg4Q/L/7X2CCXRbfJqynRJdcaNG0rlfPu1YFaVfBIe1cJE=
  on:
    repo: afeld/api.afeld.me
    branch: travis
